#!/usr/bin/sh

# Remaining storage
alias storage="df -h / --output=avail | tail -1 | xargs echo | sed 's/G/ GB/g'"

# Same as cat, but with syntax highlighting.
# Output is automatically piped to less if the text doesn't fit the terminal.
alias cat="bat -p"

# Color 'ls' output and group directories.
alias ls="exa -lh --icons --color=always --group-directories-first"
alias la="exa -lha --icons --color=always --group-directories-first"

# A search tool that combines the usability of ag with the raw speed of grep.
alias grep="rg"

# Color ip output
alias ip='ip -color=auto'

# Git
alias gs="git status"
alias gd="git diff"

# Verbosity and settings that you pretty much just always are going to want.
alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -vI"
alias mkdir="mkdir -pv"
