#!/bin/sh

# ------------------------ Startup applications ---------------------

# Kill applications that I want to restart.
killall sxhkd && killall pcloud && killall dunst

# Wallpaper
nitrogen --restore &

# Compositor (for transparency)
picom &

# Notification daemon.
dunst &

# Keyboard layout.
setxkbmap -model logitech_base -layout br -variant abnt2 &

# Input method
fcitx &

# xsettings daemon
xsettingsd &

# NetworkManager tray icon.
nm-applet &

# Hotkey daemon.
sxhkd &

# Status bar.
~/bin/polybar/launch-polybar

# For audio effects.
pulseeffects --gapplication-service &

# Cloud storage.
pcloud &

# -------------------- BSPWM CONFIG ------------------------------
bspc monitor -d I II III IV V VI
bspc config automatic_scheme      longest_side
bspc config top_padding           34
bspc config bottom_padding        0

bspc config border_width          2
bspc config window_gap            4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     reisze_corner

bspc config normal_border_color   "#14151b"
bspc config focused_border_color  "#00f5d4"
bspc config active_border_color   "#00f5d4"

# -------------------- WINDOW RULES ----------------------------
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Chromium desktop='^1' follow=on focus=on
bspc rule -a Code desktop='^2' follow=on focus=on
bspc rule -a Spotify desktop='^3' follow=on focus=on
bspc rule -a feh state=fullscreen focus=on
bspc rule -a Pavucontrol state=floating focus=on
