#!/bin/sh

# Startup applications
# Kill some applications to avoid duplicates
killall sxhkd && killall pcloud && killall pulseeffects
sleep 0.5

# Essential
nitrogen --restore &
picom &
dunst &
launch-polybar
setxkbmap -model logitech_base -layout br -variant abnt2 &
sxhkd &

# Some extras
pulseeffects --gapplication-service &
pcloud &

# BSPWM Config
bspc monitor -d firefox terminal code music files discord notes extra

bspc config automatic_scheme      longest_side
bspc config top_padding           34

bspc config border_width          2
bspc config window_gap            8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     reisze_corner

bspc config focused_border_color "#bd93f9"

# RULES
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Chromium desktop='^1' follow=on focus=on
bspc rule -a kitty desktop='^2' follow=on focus=on
bspc rule -a Code desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^4' follow=on focus=on
bspc rule -a Nemo desktop='^5' follow=on focus=on
bspc rule -a discord desktop='^6'
bspc rule -a Notable desktop='^7' follow=on focus=on
bspc rule -a Eog state=fullscreen focus=on
bspc rule -a feh state=floating focus=on
