#!/bin/sh

# Load hotkeys
sxhkd &

bspc monitor -d firefox terminal code music files discord notes extra

bspc config top_padding           34

bspc config border_width          2
bspc config window_gap            8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#bd93f9"

bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Chromium desktop='^1' follow=on focus=on
bspc rule -a kitty desktop='^2' follow=on focus=on
bspc rule -a Code desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^4' follow=on focus=on
bspc rule -a Nemo desktop='^5' follow=on focus=on
bspc rule -a discord desktop='^6'
bspc rule -a Notable desktop='^7' follow=on focus=on
bspc rule -a Standard Notes desktop='^7' follow=on focus=on

# Startup applications
nitrogen --restore &
picom &
dunst &
setxkbmap -model logitech_base -layout br -variant abnt2 &
pulseeffects --gapplication-service &
launch-polybar &
pcloud &
