# Colors (Tomorrow Night)
colors:
  # Default colors
  primary:
    background: "#1d1f21"
    foreground: "#c5c8c6"

  # Normal colors
  normal:
    black: "#1d1f21"
    red: "#cc6666"
    green: "#b5bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#c5c8c6"

  # Bright colors
  bright:
    black: "#666666"
    red: "#d54e53"
    green: "#b9ca4a"
    yellow: "#e7c547"
    blue: "#7aa6da"
    magenta: "#c397d8"
    cyan: "#70c0b1"
    white: "#eaeaea"

    # Dim colors
  dim:
    black: "#676f78"
    red: "#b55454"
    green: "#78a670"
    yellow: "#faf380"
    blue: "#707fd0"
    magenta: "#c583d0"
    cyan: "#8adaf1"
    white: "#e0e3e7"
